# SPDX-FileCopyrightText: 2006-2017 Jim Tilander
# SPDX-FileCopyrightText: 2017-2026 Lambert Clara
#
# SPDX-License-Identifier: MIT

---
version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # ignore all updates since it will most certainly break the plugin
      # compatibility with old VS versions
      - dependency-name: "Microsoft.VisualStudio.SDK"
