// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NiftyPerforce.Manifests
{
    internal sealed partial class Vsix
    {
        public const string Id = "NiftyPerforce.belkiss.3cc12a76-88f6-4e50-9ede-377ba823db79";
        public const string Name = "Nifty Perforce - belkiss' fork";
        public const string Description = @"Simple Perforce integration for Visual Studio 2022";
        public const string Language = "en-US";
        public const string Version = "3.0.5";
        public const string Author = "Lambert Clara";
        public const string Tags = "perforce";
    }
}
