// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NiftyPerforce
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidNiftyPerforcePackageString = "47a20418-f762-4ce9-a34d-a8c96611a172";
        public static Guid guidNiftyPerforcePackage = new Guid(guidNiftyPerforcePackageString);

        public const string guidNiftyPerforcePackageCmdSetString = "d8ef26a8-e88c-4ad1-85fd-ddc48a207530";
        public static Guid guidNiftyPerforcePackageCmdSet = new Guid(guidNiftyPerforcePackageCmdSetString);

        public const string guidIconsString = "d94a897e-d2f6-455e-8b67-b4cb89931439";
        public static Guid guidIcons = new Guid(guidIconsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int NiftyToolbar = 0x1000;
        public const int NiftyMenu = 0x1001;
        public const int TopLevelMenu = 0x1021;
        public const int NiftyFileTabSubMenu = 0x1023;
        public const int NiftyItemMenu = 0x1024;
        public const int NiftyProjectMenu = 0x1025;
        public const int NiftySolutionMenu = 0x1026;
        public const int NiftyFileOperationsCommandGroup = 0x3001;
        public const int NiftyFileOperationsRevertCommandGroup = 0x3002;
        public const int NiftyFileStatusCommandGroup = 0x3003;
        public const int NiftyFileTabGroup = 0x3004;
        public const int NiftyFileTabSubMenuGroup = 0x3005;
        public const int NiftyConfig = 0x0100;
        public const int NiftyEditModified = 0x0200;
        public const int NiftyEdit = 0x0300;
        public const int NiftyDiff = 0x0400;
        public const int NiftyHistory = 0x0500;
        public const int NiftyHistoryMain = 0x0501;
        public const int NiftyTimeLapse = 0x0600;
        public const int NiftyTimeLapseMain = 0x0601;
        public const int NiftyRevisionGraph = 0x0700;
        public const int NiftyRevisionGraphMain = 0x0701;
        public const int NiftyRevert = 0x0800;
        public const int NiftyRevertUnchanged = 0x0801;
        public const int NiftyShow = 0x0900;
        public const int hammer = 0x0001;
        public const int history_mode_icon = 0x0002;
        public const int p4vimage = 0x0003;
        public const int revert_toolbar_icon = 0x0004;
        public const int revision_tab_icon = 0x0005;
        public const int tb_checkout_disabled = 0x0006;
        public const int tb_checkout_hover = 0x0007;
        public const int tb_checkout = 0x0008;
        public const int tb_diff_disabled = 0x0009;
        public const int tb_diff_hover = 0x000A;
        public const int tb_diff = 0x000B;
        public const int tb_revert_disabled = 0x000C;
        public const int tb_revert_hover = 0x000D;
        public const int tb_revert = 0x000E;
        public const int tb_revgraph_disabled = 0x000F;
        public const int tb_revgraph_hover = 0x0010;
        public const int tb_revgraph = 0x0011;
        public const int tb_timelapse_disabled = 0x0012;
        public const int tb_timelapse_hover = 0x0013;
        public const int tb_timelapse = 0x0014;
    }
}